#!/bin/env ruby
# encoding: utf-8
module LinkSeeds

  def self.data
    return [
      # EMERGENCY CONTACTS

      { :name => "Samaritans",
      :url => "http://www.samaritans.org/",
      :phone => "08457 90 90 90 ",
      :location => "National",
      :opening => "24/7 365 days of the year ",
      :text => "Support by telephone, email, letter.",
      :link_type_id => 1},

      { :name => "Bath & District Samaritans",
      :url => "http://www.bathsamaritans.org/",
      :phone => "01225 460888",
      :location => "BANES",
      :opening => "",
      :text => "Support by telephone, email, letter or face to face in Bath.",
      :link_type_id => 1},

      { :name => "Intensive Services",
      :url => "http://www.awp.nhs.uk/services/community/intensive-services/",
      :phone => "01225 362700",
      :location => "BANES",
      :opening => "24/7 365 days of the year",
      :text => "Assessments for those experiencing a mental health crisis. Assessments will be given within 4 hours of referral. This service is for use of people over the age of 18.",
      :link_type_id => 1},

      { :name => "Women’s Aid",
      :url => "http://www.womensaid.org.uk/",
      :phone => "0808 2000 247",
      :location => "National/Local",
      :opening => "24/7 365 days of the year",
      :text => "Domestic abuse helpline.",
      :link_type_id => 1},

      { :name => "Saneline",
      :url => "http://www.sane.org.uk/home",
      :phone => "0845 767 8000",
      :location => "National",
      :opening => "Every day 6pm – 11pm",
      :text => "Out of hours emotional support helpline for those affected by mental health issues, inclusive of clients, carers, supporters, friends and family.",
      :link_type_id => 2},

      { :name => "Bipolar UK",
      :url => "http://www.bipolaruk.org.uk/",
      :phone => "020 7931 6480",
      :location => "London Based – Local Services available",
      :opening => "",
      :text => "Provide a range of services to enable people affected by bipolar and associated illnesses to take control of their lives. Self-help groups available in Bath.",
      :link_type_id => 3},

      { :name => "Community Arts Therapy Project (CAT)",
      :url => "http://www.community-arts-therapies.org.uk/",
      :phone => "07906 699660",
      :location => "BANES",
      :opening => "",
      :text => "A small, local charity that aims to improve the everyday lives of those affected by mental health issues through the use of Arts Therapies using Art, Drama, Dance Movement and Music Therapies to promote social inclusion, challenge stigma and discrimination and enhance well-being for all. Also work with Carers.",
      :link_type_id => 1},

      {:name => "Samaritans",
      :url => "http://www.samaritans.org/",
      :phone => "08457 90 90 90",
      :opening => "24/7 365 days of the year",
      :location => "National",
      :text => "Support by telephone, email, letter.",
      :link_type_id => 1},

      {:name => "Bath & District Samaritans",
      :url => "http://www.bathsamaritans.org/",
      :phone => "01225 460888",
      :opening => "Unknown",
      :location => "B&NES",
      :text => "Support by telephone, email, letter or face to face in Bath.",
      :link_type_id => 1},

      {:name => "Intensive Services",
      :url => "http://www.awp.nhs.uk/services/community/intensive-services/",
      :phone => "01225 362700",
      :opening => "24/7 365 days of the year",
      :location => "B&NES",
      :text => "Assessments for those experiencing a mental health crisis. Assessments will be given within 4 hours of referral. This service is for use of people over the age of 18.",
      :link_type_id => 1},


      {:name => "Women’s Aid",
      :url => "http://www.womensaid.org.uk/",
      :phone => "0808 2000 247",
      :opening => "24/7 365 days of the year",
      :location => "National/Local",
      :text => "Domestic abuse helpline.",
      :link_type_id => 1},



      # NON EMERGENCY CONTACTS


      {:name => "Citizens Advice",
      :url => "http://www.citizensadvice.org.uk/",
      :phone => "08444 111 444",
      :opening => "24/7",
      :location => "Nationwide",
      :text => "Brings you the self-help information you need to solve your problems. A vast amount of advice is provided on many topics from benefits, work, relationships and housing to debt and money management and discrimination.",
      :link_type_id => 2},

      {:name => "Citizens Advice (Advice Guide)",
      :url => "http://www.adviceguide.org.uk/england.htm",
      :phone => "08444 111 444",
      :opening => "24/7",
      :location => "Nationwide",
      :text => "Brings you the self-help information you need to solve your problems. A vast amount of advice is provided on many topics from benefits, work, relationships and housing to debt and money management and discrimination.",
      :link_type_id => 2},

      {:name => "Saneline",
      :url => "http://www.sane.org.uk/home",
      :phone => "0845 767 8000",
      :opening => "Every day 6pm – 11pm",
      :location => "National",
      :text => "Out of hours emotional support helpline for those affected by mental health issues, inclusive of clients, carers, supporters, friends and family.",
      :link_type_id => 1},

      {:name => "NHS Direct",
      :url => "www.nhsdirect.nhs.uk/",
      :phone => "0845 4647",
      :opening => "24/7 365 days of the year",
      :location => "National",
      :text => "Remotely delivered care for all healthcare concerns.",
      :link_type_id => 2},

      # Hill View Lodge
      # B&NES
      # Working age adults in-patient wards.

      {:name => "Early Intervention in Psychosis Team",
      :url => "http://www.awp.nhs.uk/services/community/early-intervention/",
      :phone => "01225 362760",
      :opening => "Mon – Fri 9am – 5pm",
      :location => "B&NES",
      :text => "Support for people between the ages of 14 – 35 experiencing their first episode of psychosis. Usually referred through GP.",
      :link_type_id => 2},

      {:name => "MindLine",
      :url => "http://www.bristolmind.org.uk/our-services/mindline-helpline",
      :phone => "0808 808 0330",
      :opening => "Unknown",
      :location => "Bristol",
      :text => "A confidential freephone helpline giving a safe place to talk if you, or someone you know, is in distress. We can also give information about mental health and local services.",
      :link_type_id => 2},


      {:name => "Bath Mind Advocacy",
      :url => "http://www.bathmind.org.uk/advocacy.htm",
      :phone => "01225 464 656",
      :opening => "Unknown",
      :location => "Local",
      :text => "A partnership in which one person represents the interests and concerns of another person as if they were their own. Our advocates can represent people directly but we encourage self advocacy by giving people the necessary help and support to represent themselves more effectively.",
      :link_type_id => 2},

      {:name => "St Mungo’s Building Bridges",
      :url => "rlillywhite@mungos.org",
      :phone => "01225 4247644",
      :opening => "Bath",
      :location => "Unknown",
      :text => "Support for people with mental health needs in the community in a variety of ways.",
      :link_type_id => 2},

      {:name => "Reach",
      :url => "http://www.dhi-online.org.uk/do/bath/the-reach-floating-support-service/",
      :phone => "01225 329 411",
      :opening => "Mon – Fri 8.30am – 7pm sat 10am – 12pm",
      :location => "Local",
      :text => "Practical and emotional support to help people live independently, including advice on housing, benefits and managing debts. Collaboratively run with DHI, Stonham and Shape.",
      :link_type_id => 2},

      {:name => "Patient Advice and Liaison Service –PALS",
      :url => "http://www.pals.nhs.uk/",
      :phone => "01225 831821",
      :opening => "Mon – Fri 9am – 5pm",
      :location => "Local",
      :text => "Help resolve concerns or problems when you are using the NHS and provide information about the NHS complaints procedure and how to get independent help if you decide you may want to make a complaint. Also provide you with information and help introduce you to agencies and support groups outside the NHS.",
      :link_type_id => 2},

      {:name => "B&NES Council",
      :url => "http://www.bathnes.gov.uk/services/adult-social-care-and-health/adults-mental-health-needs",
      :phone => "EMERGENCY OUT OF OFFICE HOURS: 01454 615165",
      :opening => "Out of Office hours",
      :location => "Local",
      :text => "This page works mostly as a directive page to other sites including the NHS however, there are also links to other health, housing, finances, carer and legal aspects.",
      :link_type_id => 2},

      {:name => "Sirona Work Development Team",
      :url => "http://www.sirona-cic.org.uk/health-care-services/mental-health/mental-health-work-development-team/",
      :phone => "01225 396646",
      :opening => "Unknown",
      :location => "B&NES",
      :text => "Provide information, advice and practical support, to enable easier access to training and work opportunities for those experiencing mental ill health.",
      :link_type_id => 2},

      {:name => "Clean Slate",
      :url => "http://cleanslateltd.co.uk/jobseekers/walk-in-centres/",
      :phone => "07530 045 313",
      :opening => "Wed & Thurs 10am-4pm",
      :location => "Unknown",
      :text => "Help you grow your confidence and skills, set goals and make plans.",
      :link_type_id => 2},

      {:name => "Genesis Trust Wood Works",
      :url => "http://www.genesistrust.org.uk/page20.html",
      :phone => "01225 429617",
      :opening => "Unknown",
      :location => "B&NES",
      :text => "provides placements to the long term unemployed who can learn to repair and refurbish furniture (donated to us by the general public). Trainees are given on the job training",
      :link_type_id => 2},

      {:name => "Options for Living",
      :url => "http://www.optionsforliving.co.uk/",
      :phone => "07738 922287",
      :opening => "Unknown",
      :location => "B&NES",
      :text => "Provide a flexible and positive approach in supporting individuals to develop and maintain their independence within a safe, relaxed and stimulating environment. ",
      :link_type_id => 2},

      {:name => "DHI – Information Takeaway",
      :url => "http://www.dhi-online.org.uk/do/bath/information-takeaway/",
      :phone => "01225 329 411",
      :opening => "Unknown",
      :location => "Bath",
      :text => "The DHI Hub at 31 Monmouth Street in Bath BA1 2AN offers a variety of services for people who want help with problems such as loneliness or lack of confidence, or who have health or money worries.",
      :link_type_id => 2},



      # SPECIFIC CONTACTS

      # Aspergers Syndrome Foundation
      # http://www.aspergerfoundation.org.uk/
      # info@aspergerfoundation.org.uk The Asperger's Syndrome Foundation c/o Littlestone Golding, Eden House, Reynolds Road, Beaconsfield HP9 2FL No telephone, email/postal enquiries only
      # Unknown
      # National
      # Information about Asperger’s Syndrome.



      {:name => "Bipolar UK",
      :url => "http://www.bipolaruk.org.uk/",
      :phone => "020 7931 6480",
      :opening => "",
      :location => "London Based – Local Services available",
      :text => "Provide a range of services to enable people affected by bipolar and associated illnesses to take control of their lives. Self-help groups available in Bath.",
      :link_type_id => 3},


      {:name => "Next Link – Domestic Abuse Support Services for Women",
      :url => "http://www.nextlinkhousing.co.uk/index.htm",
      :phone => "0117 925 0680",
      :opening => "Unknown",
      :location => "Bristol",
      :text => "Provide a range of support and housing services to women and children experiencing domestic abuse. These include safe houses / refuges, children’s services, resettlement and outreach services, a crisis response service, dedicated Black and Ethnic Minority Services and a confidential help line run in partnership with Womankind.",
      :link_type_id => 3},

      {:name => "B-EAT – Beat Eating Disorders",
      :url => "http://www.b-eat.co.uk/",
      :phone => "Adult helpline 0845 634 1414 Youthline 0845 634 7650",
      :opening => "Mon & Wed10.30am – 7.30pm Tues, Thurs & Fri 10.30am – 6.30pm",
      :location => "Nationwide",
      :text => "UKs only nationwide organisation supporting people affected by eating disorders, their family members and friends, and campaigning on their behalf. We are also the world's largest eating disorders charity.",
      :link_type_id => 3},

      {:name => "OCD Action",
      :url => "http://www.ocdaction.org.uk/",
      :phone => "0845 3906232",
      :opening => "Unknown",
      :location => "Nationwide",
      :text => "We provide support and information to anybody affected by OCD, work to raise awareness of the disorder amongst the public and frontline healthcare workers, and strive to secure a better deal for people with OCD.",
      :link_type_id => 3},

      {:name => "Triumph Over Phobia",
      :url => "http://www.topuk.org/",
      :phone => "01225 422705",
      :opening => "Unknown",
      :location => "Nationwide",
      :text => "Aims to help sufferers of phobias, obsessive compulsive disorder and other related anxiety to overcome their fears and become ex-sufferers. We do this by running a network of self-help therapy groups.",
      :link_type_id => 3},

      {:name => "Social Anxiety West",
      :url => "http://www.sawest.org/",
      :phone => "0117 230 7735 ",
      :opening => "Unknown",
      :location => "Unknown",
      :text => "Self-help group sessions. These are facilitated sessions that provide a range of social opportunities and environments where group members can make friends, gain support and make progress with increasing their confidence. ",
      :link_type_id => 3},

      {:name => "New Highway",
      :url => "http://www.newhighway.org.uk/local-services/bath.html",
      :phone => "01225 759951",
      :opening => "Everyday 9:30am – 16:30pm",
      :location => "Trowbridge Office",
      :text => "Work with the individual to help them make the changes in their drug and/or alcohol use they are seeking. Our ethos is to work towards the goals that best suit the individuals using the service. Encourage everyone to work towards harm minimisation or “safer” drug or alcohol use.",
      :link_type_id => 3},

      {:name => "SDAS",
      :url => "http://www.awp.nhs.uk/services/sdas/",
      :phone => "01225 834946",
      :opening => "Weekdays  9:00am to 5:00pm",
      :location => "Unknown",
      :text => "Counselling, psychological therapies for alcohol or drug problems",
      :link_type_id => 3},

      {:name => "CALM – Campaign Against Living Miserably",
      :url => "www.thecalmzone.net",
      :phone => "HELPLINE: 0800 58 58 58",
      :opening => "Mon – Sun 5 pm – midnight",
      :location => "National",
      :text => "FOR MEN: A helpline that takes calls from across the UK. Offer confidential, anonymous and free support, information and signposting to men anywhere in the UK through our helpline. Calls are taken by paid, trained staff who work exclusively on the CALM helpline. Are not here to represent health professionals or the mental health industry.  CALM is about, for and on behalf of men.",
      :link_type_id => 3},

      {:name => "Depression Alliance",
      :url => "http://www.depressionalliance.org/",
      :phone => "Information pack request line on 0845 123 23 20",
      :opening => "24/7",
      :location => "National",
      :text => "The leading UK charity for people with depression.  We work to relieve and to prevent this treatable condition by providing information and support services to those who are affected by it via our publications, supporter services and network of self-help groups for people affected by depression.",
      :link_type_id => 3},

      {:name => "Hearing Voices Network",
      :url => "http://www.hearing-voices.org/",
      :phone => "0114 271 8210",
      :opening => "Unknown",
      :location => "Nationwide",
      :text => "If you hear voices HVN can help – we are committed to helping people who hear voices. We offer information, support and understanding to people who hear voices and those who support them.",
      :link_type_id => 3},

      {:name => "Mothers for Mothers",
      :url => "http://www.mothersformothers.co.uk/",
      :phone => "0117 975 6006",
      :opening => "Mon-Thurs 9.30am-12.30pm + 2.30pm-9pm",
      :location => "Bristol + B&NES",
      :text => "Offers support, advice, information and most of all a listening ear for any worries or concerns you may have.",
      :link_type_id => 3},

      {:name => "Carers Centre",
      :url => "http://www.banescarerscentre.org.uk/",
      :phone => "0800 0388 885",
      :opening => "Unknown",
      :location => "B&NES",
      :text => "Expert help is available for carers who are struggling emotionally with their caring role, feeling isolated and in need of a friend or needing support when dealing with health and care planning. ",
      :link_type_id => 3},

      {:name => "Crossroads Care",
      :url => "http://www.crossroadscarebathnes.org.uk/",
      :phone => "01761 436673",
      :opening => "Unknown",
      :location => "Radstock and Bristol B&NES",
      :text => "provide expert, discreet homecare for people of all ages and with a wide range of different needs so that people can feel confident in allowing us to help them and their family in the everyday tasks they undertake.",
      :link_type_id => 3},

      {:name => "Focus Counselling",
      :url => "http://www.focusbath.com/",
      :phone => "01225 330096",
      :opening => "Mon - Thurs 8:30am - 3pm  Fri 9am -1pm",
      :location => "B&NES",
      :text => "A highly respected and busy counselling Agency in the centre of Bath. We provide affordable person-centred therapy for those people in need from Bath and its surrounding areas.",
      :link_type_id => 3},

      {:name => "Relate",
      :url => "http://www.relate.org.uk/home/index.html",
      :phone => "01225 465 593",
      :opening => "Mon 08:30 – 14:30, Tue 14:30 – 20:30, Wed 16:30 to 20:30 Thurs 11:30 – 15:30 & 16:30 – 20:30 Fri 10 – 15",
      :location => "Unknown",
      :text => "Develop and support healthy relationships by: - helping couples, families and individuals to make relationships work better - delivering inclusive, high-quality services that are relevant at every stage of life.",
      :link_type_id => 3},

      {:name => "B&NES Racial Equality Commission",
      :url => "http://www.bathnesrec.org.uk/rec/about-us",
      :phone => "01225 787918",
      :opening => "Unknown",
      :location => "Bath South Vaults",
      :text => "the lead agency promoting racial equality, and racial harmony, working towards the elimination of racial discrimination and developing the Black and Minority Ethnic sectors through a range of culturally sensitive services.",
      :link_type_id => 3},

      {:name => "Cruse",
      :url => "http://www.crusebereavementcare.org.uk/index.html",
      :phone => "01761 417250",
      :opening => "Daytime",
      :location => "Bath",
      :text => "Promotes the well-being of bereaved people and enables anyone bereaved by death to understand their grief and cope with their loss.",
      :link_type_id => 3},



      # YOUNG PEOPLE:


      {:name => "Southside",
      :url => "http://www.south-side.org.uk/",
      :phone => "01225 331243",
      :opening => "Unknown",
      :location => "Local",
      :text => "Support for families facing a range of issues including domestic violence, substance abuse, and long-term mental health issues.",
      :link_type_id => 4},

      {:name => "Child and Adolescent Mental Health Service (CAMHS)",
      :url => "http://www.oxfordhealth.nhs.uk/?directory=bath-north-east-somerset-child-and-adolescent-mental-health-services",
      :phone => "01173 604040",
      :opening => "Mon – Fri 9am – 5pm",
      :location => "Local",
      :text => "Service for those under the age of 18 with mental health issues.",
      :link_type_id => 4},

      {:name => "Off the Record",
      :url => "http://www.offtherecord-banes.co.uk/",
      :phone => "01225 312481 or text 07753 891 745",
      :opening => "Various, usually 1pm – 5pm",
      :location => "B&NES",
      :text => "Various services for young people in B&NES. Including counselling and information for those aged 10 – 25.",
      :link_type_id => 4},

      {:name => "Young Minds",
      :url => "http://www.youngminds.org.uk/",
      :phone => "Adult Help-Line: 0808 802 5544 Other:  020 7089 5050",
      :opening => "Mon - Fri 9.30 am - 4pm",
      :location => "National",
      :text => "UK’s leading charity committed to improving the emotional wellbeing and mental health of children and young people.",
      :link_type_id => 4},

      {:name => "PAPYRUS",
      :url => "http://www.papyrus-uk.org/",
      :phone => "Help-Line: 0800 068 41 41",
      :opening => "Mon-Fri 10 am - 5 pm and 7 pm - 10 pm Weekends 2 pm - 5 pm.",
      :location => "Unknown",
      :text => "Confidential Young Suicide Prevention Advice.",
      :link_type_id => 4},

      {:name => "Indigo",
      :url => "http://www.indigoproject.co.uk/",
      :phone => "0117 960 2020 Mobile: 07790645078",
      :opening => "Unknown",
      :location => "Bristol",
      :text => "An independent, user led organisation, which provides a unique and successful approach to working with young people who self-injure aged 13 – 19.",
      :link_type_id => 4},


      # ADULTS:


      {:name => "Adult Social Care B&NES – Sirona",
      :url => "http://www.sirona-cic.org.uk/",
      :phone => "01225 831400",
      :opening => "Mon – Fri 9am – 5pm",
      :location => "Local",
      :text => "Adult social care services, including floating support, mental health reablement, work development and community options.",
      :link_type_id => 5},

      {:name => "SIRONA Floating Support",
      :url => "http://www.sirona-cic.org.uk/health-care-services/mental-health/mental-health-sedgemoor-floating-support-service/",
      :phone => "01225 837092",
      :opening => "Access to service via Consultant, Social or Support worker or Psychiatric",
      :location => "Local",
      :text => "Mental Health Floating Support can provide help for up to two years to those who are vulnerable due to their mental health needs. A range of help can be provided.",
      :link_type_id => 5},

      {:name => "SANE",
      :url => "http://www.sane.org.uk/home",
      :phone => "0845 767 8000",
      :opening => "Mon – Sun 6pm – 11pm365 days of the year",
      :location => "National",
      :text => "SANE offers emotional support and information to anyone affected by mental health problems through the helpline and email services and online Support Forum where people share their feelings and experiences.",
      :link_type_id => 5},

      {:name => "AWP",
      :url => "http://www.awp.nhs.uk/",
      :phone => "01225 371411",
      :opening => "Mon- Fri 8 am – 8 pm (between 9am – 5pm provision of FULL range of services)",
      :location => "Avon and Wiltshire",
      :text => "Our recovery services are the main service to provide ongoing care, treatment and support for service users, their families, friends and supporters. The service will provide specific periods of interventions to service users requiring short or long term support to assist their recovery.",
      :link_type_id => 5},

      {:name => "AWP – Intensive Services",
      :url => "http://www.awp.nhs.uk/services/community/intensive-services/",
      :phone => "01225 325680",
      :opening => "24/7 – 365 days of the year",
      :location => "Avon and Wiltshire",
      :text => "Avon and Wiltshire Mental Health Partnership NHS Trust (AWP) provides 24 hour rapid assessment and treatment for people experiencing a mental health crisis. Provision of local support for 18 and over experiencing a breakdown in their mental health and feel that they may require an emergency response for help and support.",
      :link_type_id => 5},

      {:name => "AWP – Primary Care Liaison Services",
      :url => "http://www.awp.nhs.uk/services/community/primary-care-liason/",
      :phone => "Uknown",
      :opening => "Only referrals from GPs and other health or social care professionals",
      :location => "B&NES",
      :text => "Primary care mental health liaison service - short-term support service to help people with mental health difficulties to move forward and get on with their lives. If you have concerns about your own mental health you should first contact your GP.",
      :link_type_id => 5},


      # OLDER PEOPLE:

      {:name => "Bath Ethnic Senior Citizens Association",
      :url => "http://www.bemsca.com/",
      :phone => "01225 464 165",
      :opening => "Mon & Fri 10am - 4PM",
      :location => "Bath",
      :text => "To provide a Luncheon Club on Mondays and Fridays for Black and Ethnic Minority (B&EM) Senior Citizens. Increase awareness of available Statutory and Voluntary service provisions. Offer information and advice services to BME Senior Citizens. Offer information and advice in users’ languages.",
      :link_type_id => 6},

      {:name => "Swan Advocacy",
      :url => "http://swanadvocacy.org.uk/page/home.php",
      :phone => "01722 341851",
      :opening => "Unknown",
      :location => "Salisbury",
      :text => "To provide an independent service for vulnerable adults, such as those experiencing or recovering from mental illness, physical or sensory impairment, learning difficulties, disability or ageing. Provide a free and confidential service that is impartial and client-centred.",
      :link_type_id => 6},


      # FAMILY


      {:name => "Southside Family Project",
      :url => "http://www.south-side.org.uk/",
      :phone => "01225 331243",
      :opening => "Unknown",
      :location => "Unknown",
      :text => "We support families in Bath and North East Somerset (BANES) dealing with issues like physical disability, domestic abuse, sexual violence, substance abuse or long-term mental health problems.",
      :link_type_id => 8},


      # HOUSING:


      {:name => "Julian House",
      :url => "http://www.julianhouse.org.uk/",
      :phone => "01225 354650",
      :opening => "Unknown",
      :location => "B&NES",
      :text => "Supported housing for independent living after homelessness.",
      :link_type_id => 8},

      {:name => "Julian House Day Centre & Night Shelter",
      :url => "http://www.julianhouse.org.uk/",
      :phone => "01225 311991",
      :opening => "Unknown",
      :location => "B&NES",
      :text => "Supported housing for independent living after homelessness.",
      :link_type_id => 8},

      {:name => "Mulberry House",
      :url => "paul.hudson@mungos.org",
      :phone => "01225 427644",
      :opening => "Unknown",
      :location => "Bath",
      :text => "Support for severe and enduring mental health needs",
      :link_type_id => 8},

      {:name => "Bath Mind – Lower Oldfield Park",
      :url => "housing@bathmind.org.uk",
      :phone => "01224 448396",
      :opening => "Unknown",
      :location => "Bath",
      :text => "Residential home for long term mental health needs",
      :link_type_id => 8},

      {:name => "Solon",
      :url => "http://www.solonswha.co.uk/",
      :phone => "0117 924 4071",
      :opening => "Mon-Fri 8.30am-5pm",
      :location => "Bristol based Southwest",
      :text => "A charitable housing association set up in 1974 to provide good-quality, affordable rented housing.",
      :link_type_id => 8},

      {:name => "Stonham",
      :url => "http://www.homegroup.org.uk/careandsupport/stonhamservices/pages/stonhamservices.aspx",
      :phone => "01225 464 342",
      :opening => "Mon – Fri 9am – 5pm",
      :location => "Local/National",
      :text => "Housing and support for people with a range of needs.",
      :link_type_id => 8},

      {:name => "Rethink Floating Support",
      :url => "http://www.rethink.org/index.html",
      :phone => "07407 731108",
      :opening => "Mon-Fri 9am – 4.30pm",
      :location => "B&NES",
      :text => "Actively works with service users to facilitate move on to independent living. The service supports service users to engage in employment, volunteering and socially inclusive activity within the local community.",
      :link_type_id => 8},

      {:name => "Bath & North East Somerset Floating Support Service",
      :url => "http://www.rethink.org/how_we_can_help/our_services/south_west/bath_floating_suppor.html",
      :phone => "07407 731108 Email: bathfloatingsupport@rethink.org",
      :opening => "Mon – Fri 9.30 am – 4.30 pm",
      :location => "Local",
      :text => "Actively works with service users to facilitate move on to independent living. The service supports service users to engage in employment, volunteering and socially inclusive activity within the local community.",
      :link_type_id => 8},

      {:name => "Curo",
      :url => "http://www.curo-group.co.uk/about-us/who-we-are/",
      :phone => "01225 366000",
      :opening => "Unknown",
      :location => "B&NES",
      :text => "Providing support services to vulnerable people for over 25 years in finding affordable and manageable housing. Extra support available also if necessary.",
      :link_type_id => 8},

      {:name => "Bath Foyer - Shape",
      :url => "Unknown",
      :phone => "01225 405 004",
      :opening => "Unknown",
      :location => "Unknown",
      :text => "Accessible accommodation, support and personal development opportunities to young people by providing a package of safe, affordable, supported accommodation with housing support.",
      :link_type_id => 8},

      {:name => "Second Step",
      :url => "http://www.second-step.co.uk/",
      :phone => "0117 909 6630",
      :opening => "Unknown",
      :location => "Bristol and surrounding areas",
      :text => "Deliver recovery and well-being opportunities for people with mental health and other support needs to achieve their hopes and ambitions through providing different types of housing for people who require support to live independently.",
      :link_type_id => 8},

      {:name => "Second Step Floating Support",
      :url => "http://www.second-step.co.uk/",
      :phone => "0117 909 6630",
      :opening => "Unknown",
      :location => "Bristol and surrounding areas",
      :text => "A service we offer to people with mental health support needs who are moving into or already living in their own accommodation, such as a flat rented from a housing association or local authority. Support individual in getting used to living in their own home, settling into and getting involved in their local community and maintaining their tenancy.",
      :link_type_id => 8},

      {:name => "Sirona Home Link",
      :url => "http://www.sirona-cic.org.uk/health-care-services/mental-health/mental-health-homelink-rural-floating-support-service/",
      :phone => "01225 396042",
      :opening => "Unknown",
      :location => "B&NES",
      :text => "Offer floating support for a maximum of 18 months, providing practical, emotional and social support to promote your independence.",
      :link_type_id => 8},

      {:name => "Supported Independence",
      :url => "http://www.supportedindependence.co.uk/",
      :phone => "0117 924 8764",
      :opening => "Bath & Bristol",
      :location => "We offer a wide variety of supported living",
      :text => "services for individuals with: mental health problems, learning disabilities, challenging behaviour, autism/Asperger syndrome, alcohol abuse",
      :link_type_id => 8},



      # FINANCIAL/LEGAL:


      {:name => "National Debt Line",
      :url => "http://www.nationaldebtline.co.uk/england_wales/",
      :phone => "0808 808 4000",
      :opening => "Mon – Fri 9am – 9pm Sat 9.30am – 1pm",
      :location => "National",
      :text => "Free confidential, independent advice on how to deal with debt problems.",
      :link_type_id => 9},

      {:name => "The Independent Mental Health Advocacy –IMHA",
      :url => "http://www.bathmind.org.uk/IMHA.htm",
      :phone => "01225 316385",
      :opening => "Unknown",
      :location => "Local",
      :text => "Help understanding of rights according to Act, represent and negotiate on behalf of patients and support patients in decisions over care and treatment. To complement, not replace any other advocacy or support services available to patients.",
      :link_type_id => 9},

      {:name => "National Institute for Health and Clinical Excellence – NICE",
      :url => "http://www.nice.org.uk/",
      :phone => "0845 003 7780",
      :opening => "Unknown",
      :location => "Nationwide – London Based",
      :text => "NICE is here to help those working in the NHS, local authorities and the wider community deliver high-quality healthcare. NICE guidance sets the standards for high quality healthcare and encourages healthy living. The NHS, Local Authorities, employers, voluntary groups and anyone else involved in delivering care or promoting wellbeing, can use our guidance.",
      :link_type_id => 9},

      {:name => "NHS Consortium",
      :url => "http://www.nhsconsortium.com/",
      :phone => "01926 334740 Nationwide:08454564424",
      :opening => "24/7",
      :location => "Nationwide",
      :text => "The NHS Consortium is a scheme which offers discounted professional services to the employees of NHS hospitals, trusts and associated healthcare practices.",
      :link_type_id => 9},


      # SOCIAL CONTACTS/OTHER


      {:name => "NHS – Mental Health",
      :url => "http://www.nhs.uk/LiveWell/Mentalhealth/Pages/Mentalhealthhome.aspx",
      :phone => "Unknown",
      :opening => "Unknown",
      :location => "Nationwide",
      :text => "Access links to sites and forums focused around mental health as well as methods of improving your mental wellbeing.",
      :link_type_id => 10},

      {:name => "The Community Mental Health Team",
      :url => "Unknown",
      :phone => "01225 731631 Adults 01225 371410 Older Adults",
      :opening => "Mon – Fri 9am – 5pm",
      :location => "Local",
      :text => "Provide assessment and treatment for people living in the community who are experiencing severe mental health problems or difficulties. Enable you to continue to live in the community, according to your individual needs and wishes. CMHTs also offer support for carers, assessing their needs to help them get the help and assistance they need.",
      :link_type_id => 10},

      {:name => "Community Arts Therapy Project (CAT)",
      :url => "http://www.community-arts-therapies.org.uk/",
      :phone => "07906 699660",
      :opening => "",
      :location => "B&NES",
      :text => "A small, local charity that aims to improve the everyday lives of those affected by mental health issues through the use of Arts Therapies using Art, Drama, Dance Movement and Music Therapies to promote social inclusion, challenge stigma and discrimination and enhance well-being for all. Also work with Carers.",
      :link_type_id => 10},

      {:name => "Green Links – Bath Mind",
      :url => "http://www.bathmind.org.uk/ecominds.htm",
      :phone => "01225 316367",
      :opening => "Unknown",
      :location => "Unknown",
      :text => "Horticultural therapy: The Greenlinks project continues to be co-ordinated by the Sirona Care & Health Community Options Team. Ring for details or email: greenlinks@bathmind.org.uk.",
      :link_type_id => 10},

      {:name => "The Care Forum",
      :url => "http://www.thecareforum.org/",
      :phone => "0117 965 4444",
      :opening => "Unknown",
      :location => "Bristol and B&NES",
      :text => "Information and advice on voluntary, community and statutory services, support for adults and children in getting your voice heard about local, social and community issues.",
      :link_type_id => 10},

      {:name => "The Care Forum (Wellaware)",
      :url => "www.wellaware.org.uk/",
      :phone => "0117 965 4444",
      :opening => "Unknown",
      :location => "Bristol and B&NES",
      :text => "Information and advice on voluntary, community and statutory services, support for adults and children in getting your voice heard about local, social and community issues.",
      :link_type_id => 10},

      {:name => "Genesis",
      :url => "http://www.genesistrust.org.uk/index.html",
      :phone => "01225 463549",
      :opening => "Unknown",
      :location => "Unknown",
      :text => "Christian charity in Bath that currently runs nine projects to help the homeless and vulnerable in the city. Offer advice and support and provide longer-term opportunities.",
      :link_type_id => 10},

      {:name => "Creativity Works",
      :url => "http://www.creativityworksforeveryone.co.uk/",
      :phone => "01761 438852",
      :opening => "Unknown",
      :location => "B&NES",
      :text => "Using the power of creativity to draw communities together. Works with community groups involving people from all backgrounds and all ages, helping those with mental health issues, social issues, disadvantaged sectors of society or simply those looking for inspiration in their lives. ",
      :link_type_id => 10},

      {:name => "My Time My Space",
      :url => "http://www.creativityworksforeveryone.co.uk/what-we-do/creative-activities/my-time-my-space/",
      :phone => "01761 438852",
      :opening => "Unknown",
      :location => "B&NES",
      :text => "Supportive creative workshops for women with post natal depression. Offshoot of Creativity Works.",
      :link_type_id => 10},

      {:name => "Soundwell Music Therapy",
      :url => "http://www.soundwell.org/",
      :phone => "01225 862938",
      :opening => "Unknown",
      :location => "B&NES",
      :text => "Community-based music therapy service working in the field of adult mental health. Enhance the mental health of people experiencing emotional and mental distress by promoting and providing an inclusive, community-based service of music therapy which includes outreach, short and long term groups and individual work.",
      :link_type_id => 10},

      {:name => "Space2 (Meaningful Occupation Project) Julian House",
      :url => "http://www.julianhouse.org.uk/about/mop.html",
      :phone => "01225 354650",
      :opening => "Unknown",
      :location => "Bath",
      :text => "Clients here are given access to courses and activities, which ordinarily would not be available, because of their disconnection from mainstream society. Life skills training, basic literacy & numeracy, IT coaching sessions and even an allotment.",
      :link_type_id => 10},

      {:name => "Recycle Bike Workshop Julian House",
      :url => "http://www.julianhouse.org.uk/BikeWorkshop.htm",
      :phone => "01225 463350 ",
      :opening => "Mon-Sat 9.30 – 5pm Thurs & Fri 9.30- 6pm",
      :location => "Bath",
      :text => "Used bikes are repaired by clients and then sold to raise funds.  Much of the work at reCYCLEd is carried out by clients under the supervision of staff members. ",
      :link_type_id => 10},

      {:name => "Rose Cottage Centre",
      :url => "http://stmichaelstwerton.com/missional-communities/rose-cottage-community/",
      :phone => "01225 421 438",
      :opening => "Mon – Fri 10am – 2pm",
      :location => "Twerton - Bath",
      :text => "Community Centre - with a lounge, cafe room, learning room, large kitchen, conservatory and private garden. Rose Cottage is a friendly place; a place to unwind; a place to have a chat; a place to make friends; a place to find support and encouragement; and a place to learn. Rose Cottage Centre has Computers and broadband Internet access. Funded by churches in Bath and affiliated to St Michael's C.E. Church.",
      :link_type_id => 10},

      {:name => "Bath City Farm",
      :url => "http://bathcityfarm.org.uk/",
      :phone => "01225 481269",
      :opening => "Access to farm on foot – every day. Car Park Mon- Sat 9am – 5pm",
      :location => "Bath",
      :text => "To build a caring, healthy and cohesive community through the involvement of local people - especially those who are disadvantaged. Able to learn about sustainable farming and food growing, acquire new skills and develop new friendships through horticultural therapy – regular volunteer days.",
      :link_type_id => 10},

      {:name => "Stowey Bottom Farm",
      :url => "Unknown",
      :phone => "01275 331426",
      :opening => "Unknown",
      :location => "Bristol",
      :text => "Help people with mental health support needs into work through skills training, increased self-confidence and workplace routine. Community Learning Service",
      :link_type_id => 10},

      {:name => "City of Bath College",
      :url => "Unknown",
      :phone => "01225 352438",
      :opening => "Unknown",
      :location => "Bath",
      :text => "Learning tasters and activities to community groups in Bath & North East Somerset, to help improve opportunities to learning and work. The CLS also offers free, expert advice on learning, training and work to people aged 20 and over who have few or no qualifications.",
      :link_type_id => 10},

      {:name => "Mosaic – Bath Mind",
      :url => "http://www.bathmind.org.uk/community_outreach.htm",
      :phone => "01225 316367",
      :opening => "Weds 10am-3pm",
      :location => "Bath",
      :text => "A social group and one to one support for service users and their carers from all ethnic minority and/or cultural backgrounds.",
      :link_type_id => 10},

      {:name => "BISPAA – B&NES Inclusive Sport and Physical Activity Association",
      :url => "getactive@bathnes.gov.uk",
      :phone => "01225 831847",
      :opening => "Unknown",
      :location => "B&NES",
      :text => "Promote and increase physical activity opportunities for children and adults, with physical and learning disabilities and mental ill-health, including young carers, through consultation, promotion and activity",
      :link_type_id => 10},

      {:name => "Community Activators",
      :url => "claire_kerslake@bathnes.gov.uk",
      :phone => "01225 396429",
      :opening => "Unknown",
      :location => "Bath",
      :text => "Helping you to become more active.  Being active is very important to your current health status and to help prevent chronic health conditions in the future.",
      :link_type_id => 10},

      {:name => "Bath Mad Hatters",
      :url => "bathmadhatters@hotmail.co.uk",
      :phone => "Unknown",
      :opening => "Unknown",
      :location => "Unknown",
      :text => "Service users magazine promoting positive mental health.",
      :link_type_id => 10},

      {:name => "Live Life to the Full",
      :url => "http://www.llttf.com/index.php enquiries@livinglifetothefull.com ",
      :phone => "Unknown",
      :opening => "Unknown",
      :location => "Nationwide",
      :text => "Self help website forum ‘helping you to help yourself.’",
      :link_type_id => 10},

      {:name => "FIS – Family Information Service",
      :url => "fis@bathnes.gov.uk  ",
      :phone => "0800 073 1214 ",
      :opening => "Mon - Thurs 8.45am to 4.45pm & Fri 8.30am to 4.30pm - answerphone out of hours",
      :location => "Unknown",
      :text => "Working to support local families with information and choices. The Information Team will answer your calls to the helpline and deal with any emails you send requesting information.",
      :link_type_id => 10},

      {:name => "Bath Mind – Befriending Service",
      :url => "http://www.bathmind.org.uk/befriending.htm",
      :phone => "01225 464656",
      :opening => "Unknown",
      :location => "Bath",
      :text => "Aims to help by establishing one to one supportive relationships between a trained volunteer and people who are lonely and isolated.",
      :link_type_id => 10},

      {:name => "Chew Valley and Keynsham Befrienders",
      :url => "http://www.befriender.org.uk/",
      :phone => "01275 472798",
      :opening => "Unknown",
      :location => "Unknown",
      :text => "Free to those in Chew Valley & Keynsham. A small voluntary organisation operating in parts of North Somerset and Bath & North East Somerset. We support individuals (over 18s) and their families, who have mental health problems or are experiencing mental distress.",
    :link_type_id => 10}
    ]
  end
end


